name: Merge Staging Build Next.js App

on:
  pull_request:
    branches:
      - staging-experimental
    types: [closed]

concurrency:
  group: staging-build
  cancel-in-progress: true

jobs:
  update-prerelease:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: git fetch --tags --all

      - name: Set base and head branch for diff
        id: branch-info
        run: |
          echo "base=origin/${{ github.event.pull_request.base.ref }}" >> "$GITHUB_OUTPUT"
          echo "head=origin/${{ github.event.pull_request.head.ref }}" >> "$GITHUB_OUTPUT"

      - name: Extract prerelease version from output
        id: prerelease
        run: |
          chmod +x ./scripts/get-next-prerelease.sh
          VERSION=$(./scripts/get-next-prerelease.sh ${{ steps.branch-info.outputs.base }} ${{ steps.branch-info.outputs.head }} | grep BETA_VERSION | cut -d'=' -f2)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "${{ steps.prerelease.outputs.version }}"
          git push origin "${{ steps.prerelease.outputs.version }}"
